# copyright: 2022 EUMETSAT
# license: LICENSE.txt
name: cmts_ocean_case_studies
channels:
  - conda-forge
  - cmts
  - eumetsat
  - coecms
dependencies:
  - conda-forge::python=3.9
  - conda-forge::notebook=6.4.12
  - conda-forge::xarray
  - conda-forge::netcdf4
  - conda-forge::shapely
  - conda-forge::matplotlib
  - conda-forge::cartopy
  - conda-forge::jupyter_contrib_nbextensions
  - cmts::hda
  - cmts::eumartools
  - eumetsat::eumdac
  - coecms::xmhw
