name: cmts_ocean_case_studies
channels:
  - conda-forge
  - cmts
  - eumetsat
dependencies:
  - conda-forge::python=3.9
  - conda-forge::notebook
  - conda-forge::xarray
  - conda-forge::netcdf4
  - conda-forge::shapely
  - conda-forge::matplotlib
  - conda-forge::cartopy
  - conda-forge::jupyter_contrib_nbextensions
  - conda-forge::bokeh
  - cmts::hda
  - cmts::eumartools
  - eumetsat::eumdac
