# copyright: 2023 EUMETSAT
# license: LICENSE.txt
name: cmts_ocean_case_studies
channels:
  - conda-forge
  - cmts
  - eumetsat
  - coecms
dependencies:
  - conda-forge::python=3.9
  - conda-forge::jupyterlab
  - conda-forge::xarray
  - conda-forge::netcdf4
  - conda-forge::shapely
  - conda-forge::matplotlib
  - conda-forge::cartopy
  - conda-forge::ipywidgets
  - conda-forge::jupyter_nbextensions_configurator
  - conda-forge::opencv
  - conda-forge::requests
  - conda-forge::beautifulsoup4
  - conda-forge::lxml
  - conda-forge::pydap>3.3.0
  - conda-forge::owslib
  - conda-forge::bokeh
  - conda-forge::scipy
  - conda-forge::pandas
  - cmts::hda=1.1
  - cmts::eumartools
  - eumetsat::eumdac=2.0.1
  - coecms::xmhw
  - pip
  - pip:
    - wust