# copyright: 2023 EUMETSAT
# license: LICENSE.txt
name: cmts_ocean_case_studies
channels:
  - conda-forge
  - cmts
  - eumetsat
  - coecms
dependencies:
  - conda-forge::python=3.9
  - conda-forge::notebook=6.4.12
  - conda-forge::xarray=2022.3.0
  - conda-forge::netcdf4
  - conda-forge::shapely
  - conda-forge::matplotlib
  - conda-forge::cartopy
  - conda-forge::jupyter_contrib_nbextensions
  - conda-forge::motuclient
  - conda-forge::opencv
  - conda-forge::requests
  - conda-forge::beautifulsoup4
  - conda-forge::owslib
  - cmts::hda=0.3.7
  - cmts::eumartools
  - eumetsat::eumdac
  - coecms::xmhw=0.8.0